# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'IOSInterViewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveCocoa'
  # Pods for IOSInterViewApp

  target 'IOSInterViewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSInterViewAppUITests' do
    # Pods for testing
  end

end
